name: PyPI 📦 Distribution (Linux only, Py3.10)

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels for Python 3.10 on manylinux2014
        shell: bash
        run: |
          set -euxo pipefail
          if [ "${{ matrix.arch }}" = "i686" ]; then
            IMAGE="quay.io/pypa/manylinux2014_i686"
          else
            IMAGE="quay.io/pypa/manylinux2014_x86_64"
          fi

          docker run --rm -v "$PWD":/work "$IMAGE" bash -c "
            /opt/python/cp310-cp310/bin/python -m pip install --upgrade pip wheel 'setuptools<70' &&
            cd /work/bindings/python &&
            /opt/python/cp310-cp310/bin/python setup.py bdist_wheel
          "

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.arch }}
          path: ${{ github.workspace }}/bindings/python/dist/*

  publish:
    needs: [build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-linux-*
          merge-multiple: true
          path: dist
