name: PyPI 📦 Distribution （Windows）
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x32, x64]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Set up MSVC x86 (VS 2019)
      if: matrix.platform == 'x32'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
        toolset: 14.29
    - name: Set up MSVC x64 (VS 2019)
      if: matrix.platform == 'x64'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.29
  
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
    
    - name: Build distribution 📦
      shell: bash 
      run: |
        if [ ${{ matrix.platform }} == 'x32' ]; then
             cd bindings/python && python setup.py build -p win32 bdist_wheel -p win32
        else
             cd bindings/python && python setup.py bdist_wheel
        fi
    
    - uses: actions/upload-artifact@v4
      with:
         path: ${{ github.workspace }}/bindings/python/dist/*
